#!/bin/bash
#vim:syntax=shell

# Install antibody
if [[ ! -f /usr/local/bin/antibody ]]; then
  curl -sL git.io/antibody | sh -s
fi

# Install miniconda
miniconda=Miniconda3-latest-Linux-x86_64.sh

if [[ ! -f $miniconda ]]; then
    cd $HOME
    wget --quiet https://repo.anaconda.com/miniconda/$miniconda
    chmod +x $miniconda
    ./$miniconda -b -p $HOME/miniconda
fi
