#!/bin/bash
#vim:syntax=shell

# Install antibody
if [[ ! -f /usr/local/bin/antibody ]]; then
  curl -sL git.io/antibody | sh -s
fi


echo "[+] Installing miniconda .."

arch = $(uname -m)
if [ "$arch" == "i686" ]; then
  miniconda=Miniconda3-latest-Linux-x86.sh
else
  miniconda=Miniconda3-latest-Linux-x86_64.sh
fi
echo "[+] Using $miniconda .."


if [[ ! -f $miniconda ]]; then
    cd $HOME
    wget --quiet https://repo.anaconda.com/miniconda/$miniconda
    chmod +x $miniconda
    ./$miniconda -b -p $HOME/miniconda3

    source miniconda3/bin/activate
    # development dependencies to run neovim without problems
    pip install pynvim black isort ipython python-language-server
fi
echo "[+] Installation completed."

echo "[+] Installing rbenv .."
if [[ ! -d $HOME/.rbenv ]]; then
  curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
  export PATH=$HOME/.rbenv/bin:$PATH
  rbenv install 2.6.2
fi
echo "[+] Installation completed."

echo "[+] Installing neovim and its plugins .."
if command -v nvim >/dev/null 2>&1; then
  nvim -u $HOME/.config/nvim/config/01.plugins.vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall' &> /dev/null
fi
echo "[+] Installation completed."
